### ISSUE TITLE
Method out of date

### ISSUE THREAD

**Issue by zhangle1** [erikcaffrey/People-MVVM#1]
Hello, I am a novice, English is not very good,... I found your project example is well written, but I suggest that the use of gradle version I databinding new method.
@BindingAdapter ({imageUrl}) instead of @BindingAdapter ({bind:imageUrl})
Android:onClick= "@{peopleViewModel:: onItemClick}" instead of
Android:onClick= "@{peopleViewModel.onItemClick}
Thank you for your code. O(∩_∩)O

**Comment by erikcaffrey** [comment]
The warning occurs if you use any namespace prefix, If you omit the namespace, like so:
@BindingAdapter({"imageUrl"}) now it is solved, Thanks for the observation.
