### ISSUE TITLE
Well done, can you explain how can i add infinite scroll to this 

### ISSUE THREAD

**Issue by khanimdad** [erikcaffrey/People-MVVM#16]
I browsed so many MVVM project and this one seems very relevant.

**Comment by erikcaffrey** [comment]
This scrolling logic is handled from your activity or fragment with the adapter & layout manager, `ViewModel` responsibility is just to orchestrate the data to be displayed in UI basically the UI logic. 

You can research about Paging Library maybe you can found it useful -> https://github.com/erikcaffrey/Movies-PagingLibrary-Arch-Components
