### ISSUE TITLE
Typo i gues

### ISSUE THREAD

**Issue by SDemonUA** [erikcaffrey/People-MVVM#21]
https://github.com/erikcaffrey/People-MVVM/blob/7b3cc8f3648aba4f313a261a2b9c167089bbe7c7/app/src/main/java/com/example/jhordan/people_mvvm/viewmodel/PeopleDetailViewModel.java#L40

**Comment by erikcaffrey** [comment]
https://github.com/erikcaffrey/People-MVVM/pull/28 Fixed!
