### ISSUE TITLE
Shouldn't ItemPeopleViewModel and DetailPeopleViewModel merge

### ISSUE THREAD

**Issue by kellyrose0902** [erikcaffrey/People-MVVM#9]
They have the same data, why you code it in 2 different file?
It's can all be PeopleDataViewModel or sth, and whether if it's a recyclerview or a detail, the UI can read data from the same view model

**Comment by erikcaffrey** [comment]
it was my first iteration and I would prefer use a Repository Pattern instead of recycle a ViewModel. thanks for your comment.
